name: snsinahub-valet/Cirecle-migration/start-step-2
on:
  push:
    branches:
    - main
jobs:
  step-2:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    env:
      DOCKER_LOGIN: ''
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Docker build
      run: |-
        docker build \
        -t docker.io/snsinahub-valet/aws-migration:$GITHUB_SHA
      timeout-minutes: 10
    - run: 'echo "Digest is: $(</tmp/digest.txt)"'
        
