name: snsinahub-valet/Cirecle-migration/start-step-2
on:
  workflow_dispatch:
jobs:
  step-2:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    env:
      DOCKER_LOGIN: ''
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      id: qemu
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Docker build
      run: |-
        docker build \
        -t docker.io/snsinahub-valet/aws-migration:$GITHUB_SHA
      timeout-minutes: 10
    - run: 'echo "Digest is: $(</tmp/digest.txt)"'
        
